version: '3.8'

services:
  proxy: 
    image: 'haproxytech/haproxy-ubuntu:2.4'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coollabs-dev
    volumes:
      - './haproxy-dev.cfg:/usr/local/etc/haproxy/haproxy.cfg'
      - '/data/coolify/haproxy:/data/coolify/haproxy'
    ports: 
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8404
        published: 8404
        protocol: tcp
        mode: host
      - target: 5555
        published: 5555
        protocol: tcp
        mode: host
  redis:
    image: 'bitnami/redis:6.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coollabs-dev
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

networks:
  coollabs-dev:
    driver: overlay
    name: coollabs-dev
    external: true
