version: '3.8'

services:
  coolify:
    image: coolify:v2.0.0-rc.1
    container_name: coolify
    ports: 
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - './db:/app/db'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - APP_ID=${APP_ID}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - "coolify"
  redis:
    image: bitnami/redis:6.2
    container_name: coolify-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - "coolify"

networks:
  coolify:
    attachable: true
    name: coolify
