version: '3.8'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coollabs-dev
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    # volumes:
    #   - coollabs-redis-data:/bitnami/redis/data

# volumes:
# coollabs-redis-data: {}

networks:
  coollabs-dev:
    driver: overlay
    name: coollabs-dev
    external: true
