version: '3.8'

services:
  coolify:
    image: coollabsio/coolify:2.0.0-rc.1
    container_name: coolify
    ports: 
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - './db:/app/db'
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file:
      - ".env"
    networks:
      - coolify-infra
  redis:
    image: bitnami/redis:6.2
    container_name: coolify-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coolify-infra

networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
