version: '3.8'

services:
  haproxy: 
    image: haproxytech/haproxy-ubuntu:2.4
    container_name: coolify-haproxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify-infra
    volumes:
      - './data/haproxy/:/usr/local/etc/haproxy/'
    ports: 
      - "80:80"
      - "443:443"
      - "8404:8404"
      - "5555:5555"

networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
