version: '3.8'

services:
  coolify:
    container_name: coolify
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '~/.pnpm-store/:/root/.pnpm-store/'
      - '.:/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - coollabs-dev
  haproxy: 
    image: 'haproxytech/haproxy-ubuntu:2.4'
    container_name: coolify-haproxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coollabs-dev
    volumes:
      - './tmp/haproxy/:/usr/local/etc/haproxy/'
    ports: 
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8404
        published: 8404
        protocol: tcp
        mode: host
      - target: 5555
        published: 5555
        protocol: tcp
        mode: host
  redis:
    image: 'bitnami/redis:6.2'
    container_name: coolify-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coollabs-dev
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

networks:
  coollabs-dev:
    driver: overlay
    name: coollabs-dev
    external: true
